apiVersion: v1
kind: Service
metadata:
  labels:
    app: zahori-process
  name: zahori-process
spec:
  ports:
    - name: 8765-8765
      port: 8765
      protocol: TCP
      targetPort: 8765
  selector:
    app: zahori-process
