spec:
  template:
    spec:
      containers:
        - env:
            - name: ZAHORI_CONSUL_HOST
              value: openzahori-consul-service
            - name: ZAHORI_SELENOID_HOST
              value: moon.moon.svc.cluster.local
          envFrom:
            - configMapRef:
                name: openzahori-zahori-config
          image: zahoriaut/zahori-process:0.1.12
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/liveness
              port: 8765
              scheme: HTTP
            initialDelaySeconds: 120
            successThreshold: 1
          name: zahori
          ports:
            - containerPort: 8765
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/readiness
              port: 8765
              scheme: HTTP
            initialDelaySeconds: 20
            successThreshold: 1
          resources:
            limits:
              cpu: 1000m
              memory: 500Mi
            requests:
              cpu: 300m
              memory: 256Mi